---
- name: Uninstall unofficial docker packages for Debian
  ansible.builtin.apt:
    name: "{{ __docker_engine__debian_unofficial_packages }}"
    state: absent
  when: ansible_distribution == 'Debian'

- name: Uninstall unofficial docker packages for Ubuntu
  ansible.builtin.apt:
    name: "{{ __docker_engine__ubuntu_unofficial_packages }}"
    state: absent
  when: ansible_distribution == 'Ubuntu'

- name: Ensure keyrings directory exists
  ansible.builtin.file:
    path: "{{ __docker_engine__keyrings_directory }}"
    state: directory
    owner: root
    group: root
    mode: "755"

- name: Deploy docker repository key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    dest: "{{ __docker_engine__repository_key }}"
    owner: root
    group: root
    mode: "644"

- name: Get system's architecture
  ansible.builtin.command: dpkg --print-architecture
  register: docker_engine__system_architecture
  changed_when: false

- name: Deploy docker repository
  ansible.builtin.apt_repository:
    repo: |
      deb [arch={{ docker_engine__system_architecture.stdout }} signed-by={{ __docker_engine__repository_key }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present
    update_cache: true
    filename: docker

- name: Deploy docker
  ansible.builtin.apt:
    name: "{{ __docker_engine__official_packages }}"
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: Add users to the docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items:
    - "{{ docker_engine__users }}"
